stages:
    - build
    - test
    - package
    - deploy

pep8:
    stage: test
    image: fedora-python3
    tags:
        - docker
    script:
        - tox -e pep8

fedora-rpm:
    stage: package
    tags:
        - docker
    image: fedora-python3
    script:
        - python3 setup.py sdist
        - rpmbuild --define "_sourcedir $(pwd)/dist" --define "_rpmdir $(pwd)/rpms" --define "buildid .$(date +%Y%m%d%H%M)" -bb impera.spec
    artifacts:
        paths:
            - dist/
            - rpms/

publish-rpm:
    stage: deploy
    tags:
        - shell
    dependencies:
        - fedora-rpm
    script:
        - find
        - pwd
        - id
