stages:
    - build
    - test
    - package
    - deploy

tox:
    stage: test
    image: fedora-python3
    tags:
        - docker
    script:
        - tox

fedora-rpm:
    stage: package
    tags:
        - docker
    image: fedora-python3
    script:
        - python3 setup.py egg_info -RDb "b$(date +%Y%m%d%H%M)" sdist
        - rpmbuild --define "_sourcedir $(pwd)/dist" --define "_rpmdir $(pwd)/rpms" --define "buildid .$(date +%Y%m%d%H%M)" -bb impera.spec
    artifacts:
        paths:
            - dist/
            - rpms/

publish-rpm:
    stage: deploy
    tags:
        - shell
    dependencies:
        - fedora-rpm
    script:
        - for f in rpms/noarch/*; do RPM=$(basename $f); ssh reposhell@packages.inmanta.com "put rpms/inmanta/$CI_BUILD_REF_NAME/fedora/$RPM" < rpms/noarch/$RPM; done
