stages:
    - build
    - test
    - package
    - deploy

pep8:
    stage: test
    image: fedora-python3
    tags:
        - docker
    script:
        - tox -e pep8

rpm:
    stage: package
    tags:
        - docker
    image: fedora-python3
    script:
        - python3 setup.py sdist
    artifacts:
        paths:
            - dist/
