dashboard:
    image: inmanta-dashboard
    links:
        - server
    ports:
        - "8000:8000"

server:
    build: .
    ports:
        - "8888:8888"
    links:
        - mongo
mongo:
    image: mongo
